spring.application.name=demo1
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
spring.datasource.username=marketplace_user
spring.datasource.password=marketplace_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
